
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: full_stuck_project_development
  username: postgres
  password: sadaf313
  port: 5432

  
test:
  <<: *default
  database: full_stuck_project_test
  username: postgres
  password: 5001


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: full_stuck_project_production
  username: full_stuck_project
  password: <%= ENV["HELLO_RAILS_DATABASE_PASSWORD"] %>